name: Build binaries and trigger deployments

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.5"

      - name: Install Autogit
        run: |
          curl -L $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/darklab8/autogit/releases/latest | sed "s/releases\/tag/releases\/download/")/autogit-linux-amd64 -o /usr/local/bin/autogit && chmod 777 /usr/local/bin/autogit

      - name: Checkout git repo with tags and commits for autogit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: build
        run: task build:bins

      - name: Print release changelog
        id: changelog
        run: |
          echo 'artifact<<EOF' >> $GITHUB_OUTPUT
          autogit changelog >> "$GITHUB_OUTPUT"
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          body: ${{ steps.changelog.outputs.artifact }}
          files: |
            dist/redock-linux-amd64
            dist/redock-linux-arm64
            dist/redock-macos-amd64
            dist/redock-macos-arm64
            dist/redock-windows-amd64.exe
            dist/redock-windows-arm64.exe

      - uses: webiny/action-post-run@2.0.1
        name: Test tear down
        with:
          run: |
            docker stop testtarget ; docker rm testtarget
      - name: Test setup
        run: docker run -d -it --name=testtarget ubuntu:22.04 sleep infinity

      - name: Install redock
        run: curl -L $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/darklab8/redock/releases/latest | sed "s/releases\/tag/releases\/download/")/redock-linux-amd64 -o /usr/local/bin/redock && chmod 777 /usr/local/bin/redock

      - name: Run redock
        run: redock --ctr=testtarget --strict_pull=true
